#!/bin/bash

set -euo pipefail

find_script() {
    local script_dir
    script_dir="$(cd "$(dirname "$0")" && pwd)"

    if [ -x "${script_dir}/check_private_paths.sh" ]; then
        printf '%s\n' "${script_dir}/check_private_paths.sh"
        return
    fi

    if [ -x "scripts/check_private_paths.sh" ]; then
        printf '%s\n' "scripts/check_private_paths.sh"
        return
    fi

    if [ -n "${TEST_SRCDIR:-}" ]; then
        local found
        found="$(find "$TEST_SRCDIR" -path '*/scripts/check_private_paths.sh' -print -quit)"
        if [ -n "$found" ]; then
            printf '%s\n' "$found"
            return
        fi
    fi

    echo "error: cannot locate check_private_paths.sh" >&2
    exit 1
}

SCRIPT="$(find_script)"
TMPDIR="${TEST_TMPDIR:-$(mktemp -d)}"
FAILURES=0

make_diff() {
    local added_line="$1"
    printf 'diff --git a/t b/t\n'
    printf '+++ b/t\n'
    printf '@@ -0,0 +1 @@\n'
    printf '+%s\n' "$added_line"
}

run_stdin_case() {
    local added_line="$1"
    shift
    make_diff "$added_line" | "$@"
}

record_result() {
    local expected="$1"
    local name="$2"
    local status="$3"
    local output="$4"

    if [ "$status" -eq "$expected" ]; then
        return
    fi

    echo "FAIL: ${name}" >&2
    echo "expected status ${expected}, got ${status}" >&2
    if [ -n "$output" ]; then
        echo "$output" >&2
    fi
    FAILURES=$((FAILURES + 1))
}

expect_pass() {
    local name="$1"
    shift
    local output
    local status

    set +e
    output="$("$@" 2>&1)"
    status=$?
    set -e

    record_result 0 "$name" "$status" "$output"
}

expect_fail() {
    local name="$1"
    shift
    local output
    local status

    set +e
    output="$("$@" 2>&1)"
    status=$?
    set -e

    if [ "$status" -ne 0 ]; then
        return
    fi

    echo "FAIL: ${name}" >&2
    echo "expected non-zero status, got 0" >&2
    if [ -n "$output" ]; then
        echo "$output" >&2
    fi
    FAILURES=$((FAILURES + 1))
}

home_path="/Users/"'alice/project/file.txt'
linux_home_path="/home/"'alice/project/file.txt'
temp_path="/private/var/"'folders/39/example/file.txt'
extra_name="local""person"

expect_pass "clean stdin diff" \
    run_stdin_case "repo-relative/path only" env USER= LOGNAME= HOME= "$SCRIPT" --stdin

expect_fail "macOS user home path in added line" \
    run_stdin_case "$home_path" env USER= LOGNAME= HOME= "$SCRIPT" --stdin

expect_fail "Linux user home path in added line" \
    run_stdin_case "$linux_home_path" env USER= LOGNAME= HOME= "$SCRIPT" --stdin

expect_fail "macOS per-user temporary path in added line" \
    run_stdin_case "$temp_path" env USER= LOGNAME= HOME= "$SCRIPT" --stdin

expect_pass "username inside identifier is allowed" \
    run_stdin_case "${extra_name}ViewController" env USER= LOGNAME= HOME= PRIVATE_PATH_EXTRA_NAMES="$extra_name" "$SCRIPT" --stdin

expect_fail "username in prose is blocked" \
    run_stdin_case "written by ${extra_name} today" env USER= LOGNAME= HOME= PRIVATE_PATH_EXTRA_NAMES="$extra_name" "$SCRIPT" --stdin

expect_fail "extra usernames parse comma and space separators" \
    run_stdin_case "generated by secondname" env USER= LOGNAME= HOME= PRIVATE_PATH_EXTRA_NAMES="firstname,secondname thirdname" "$SCRIPT" --stdin

expect_pass "empty user environment does not add noisy username patterns" \
    run_stdin_case "clean diff with empty user environment" env USER= LOGNAME= HOME= "$SCRIPT" --stdin

expect_fail "cached staged content propagates violations" bash -c '
    set -euo pipefail
    repo="$(mktemp -d "'"$TMPDIR"'/private-paths.XXXXXX")"
    cd "$repo"
    git init -q
    printf "%s\n" "$1" > leak.txt
    git add leak.txt
    env USER= LOGNAME= HOME= "$2" --cached
' bash "$home_path" "$SCRIPT"

if [ "$FAILURES" -ne 0 ]; then
    exit 1
fi
